from detectron2.config import CfgNode as CN

def add_bodyhands_config(cfg):

    _C = cfg

    _C.MODEL.ROI_OVERLAP_ESTIMATION_HEAD = CN()
    _C.MODEL.ROI_OVERLAP_ESTIMATION_HEAD.NAME=""
    _C.MODEL.ROI_OVERLAP_ESTIMATION_HEAD.CONV_DIMS = []
    _C.MODEL.ROI_OVERLAP_ESTIMATION_HEAD.CONV_NORM = ""
    _C.MODEL.ROI_OVERLAP_ESTIMATION_HEAD.FC_DIM = [1024, 4]
    _C.MODEL.ROI_OVERLAP_ESTIMATION_HEAD.POOLER_RESOLUTION = 7
    _C.MODEL.ROI_OVERLAP_ESTIMATION_HEAD.POOLER_SAMPLING_RATIO = 0
    _C.MODEL.ROI_OVERLAP_ESTIMATION_HEAD.POOLER_TYPE = "ROIAlignV2"
    _C.MODEL.ROI_OVERLAP_ESTIMATION_HEAD.LOSS_WEIGHT = 1.0 

    _C.MODEL.ROI_POSITIONAL_DENSITY_HEAD = CN()
    _C.MODEL.ROI_POSITIONAL_DENSITY_HEAD.NAME=""
    _C.MODEL.ROI_POSITIONAL_DENSITY_HEAD.CONV_DIMS = []
    _C.MODEL.ROI_POSITIONAL_DENSITY_HEAD.CONV_NORM = ""
    _C.MODEL.ROI_POSITIONAL_DENSITY_HEAD.FC_DIM = [1024, 4]
    _C.MODEL.ROI_POSITIONAL_DENSITY_HEAD.POOLER_RESOLUTION = 7
    _C.MODEL.ROI_POSITIONAL_DENSITY_HEAD.POOLER_SAMPLING_RATIO = 0
    _C.MODEL.ROI_POSITIONAL_DENSITY_HEAD.POOLER_TYPE = "ROIAlignV2"
    _C.MODEL.ROI_POSITIONAL_DENSITY_HEAD.LOSS_WEIGHT = 1.0 